### ISSUE TITLE
Cant get thumbnail url 

### ISSUE THREAD

**Issue by radmotivator** [voceconnect/multi-post-thumbnails#100]
Hi there,

```
<?php if (class_exists('MultiPostThumbnails')) :
    MultiPostThumbnails::the_post_thumbnail(
        get_post_type(),
        'secondary-image'
    );
endif; ?>
```
Works fine to display the thumbnail but when I change to
```
<?php if (class_exists('MultiPostThumbnails')) :
    MultiPostThumbnails::get_post_thumbnail_url(
        get_post_type(),
        'secondary-image'
    );
endif; ?>
```
Nothing is returned.  Does this work in 4.5.1?

Many thanks

**Comment by chrisscott** [comment]
Like core's `get_` vs. `the_` template tags, `MultiPostThumbnails::get_post_thumbnail_url()` doesn't echo. So you'll either need to echo before it or assign it to a variable for future use.
