### ISSUE TITLE
Doesn t work on wp 4.5.3

### ISSUE THREAD

**Issue by nemanjaradevic** [voceconnect/multi-post-thumbnails#102]
http://awesomescreenshot.com/05a5yzfoc2

adding any kind of media pictures dont  appear in the backend 

http://awesomescreenshot.com/04a5yzfz91

but when i instert it doesn t appear in WP backend or frontend basically the attachment doesn t work

**Comment by chrisscott** [comment]
Are there any errors in your browser's console when you try to select the image or when an image is selected in the media manager?

FYI, I've confirmed this plugin still works on 4.5.3.

**Comment by nemanjaradevic** [comment]
POST http://www.chronostravel.com/wp-admin/admin-ajax.php
	
418 Unknown
		256ms	
load-sc...r=4.5.3 (line 4)
HeadersPostResponseHTML

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>418 unused</title>
</head><body>
<h1>unused</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 webmaster@chronostravel.com and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>

POST http://www.chronostravel.com/wp-admin/admin-ajax.php
	
200 OK
		690ms

**Comment by chrisscott** [comment]
For the first post to admin-ajax, can you see what data is being posted (likely the Headers or Post link/tabs in the error)?

**Comment by nemanjaradevic** [comment]
I don t know how to do that, i will try and disable all other plugins and
test, do you think the theme could be faylty too? It s an old twentytwelve
i think
