### ISSUE TITLE
How to use the argument "add_image_size()"

### ISSUE THREAD

**Issue by andresglx** [voceconnect/multi-post-thumbnails#109]
Hi there,

Could you please tell me how to use correctly the argument "add_image_size()" ?

This is the piece of code I am using and it works but on debug mode on it returns the following warning:

```
<?php if (class_exists('MultiPostThumbnails')) :
    MultiPostThumbnails::the_post_thumbnail(
      get_post_type(),
      'hover-image',
      add_image_size(),
      'team-member'
    );
    endif;
?>
```

> Warning: Missing argument 1 for add_image_size(), called in /Applications/MAMP/htdocs/myproject/wp-content/themes/mytheme/sections/onepage-team.php on line 23 and defined in /Applications/MAMP/htdocs/myproject/wp-includes/media.php on line 246
> 
> Notice: Undefined variable: name in /Applications/MAMP/htdocs/myproject/wp-includes/media.php on line 249

Cheers!

**Comment by chrisscott** [comment]
You'll want to add the image size ([docs](https://developer.wordpress.org/reference/functions/add_image_size/)) separately and reference the size as noted in the [plugin docs](https://github.com/voceconnect/multi-post-thumbnails/wiki#display-the-thumbnail).

**Comment by andresglx** [comment]
Hi Chrissscott,

Yes I did that. Could you paste an example of the code for your plugin supposing I have declared the image size on functions.php  , please?

Thanks,

**Comment by chrisscott** [comment]
Have you looked at [the docs](https://github.com/voceconnect/multi-post-thumbnails/wiki#display-the-thumbnail)? If there's something there that's unclear, let me know and I'll see about updating the docs.
