### ISSUE TITLE
Issue with the latest version of Wordpress 4.6.1

### ISSUE THREAD

**Issue by sgsmit** [voceconnect/multi-post-thumbnails#110]
Since I have upgraded my website to the latest version of wordpress 4.6.1 my secondary image is not working (not showing) om my homepage. Are you having any plans to test the plugin and fix the issue?

kind regards,
sgsmit

**Comment by chrisscott** [comment]
This is the first report of it not working in 4.6.1 and in a test on a local install just upgraded to 4.6.1 it is still working. 

Are you getting any PHP errors in your logs?

**Comment by dsvoba** [comment]
It doesn't work for me as well. Also not getting any PHP errors.
