### ISSUE TITLE
Control the amount of extra featured image's

### ISSUE THREAD

**Issue by Eelcomartens** [voceconnect/multi-post-thumbnails#112]
Hello.

The standard is set to add 4 more featured image's. Where can i make it one and not four extra?

Can anyone help me with that? i'm using it ass a direct funtion and not a plugin.

In functions I have: require_once('library/multi-post-thumbnails.php');

the rest in non-edited.

**Comment by chrisscott** [comment]
Can you clarify? The only featured images that will be added are the ones you register by instantiating an instance of the `MultiPostThumbnails` class. It sounds like wherever your code is that is doing that is being called multiple times.
