### ISSUE TITLE
Option for thumbnail description in backend

### ISSUE THREAD

**Issue by mrjulian** [voceconnect/multi-post-thumbnails#115]
Hey, is there a chance to get a thumbnail description in the backend? I would like to display the recommend image size and so on.

Many thanks.

Julian

**Comment by chrisscott** [comment]
You can use [`MultiPostThumbnails::get_post_thumbnail_id()`](https://github.com/voceconnect/multi-post-thumbnails/wiki/Functions-and-Template-Tags#get_post_thumbnail_id) to get the ID and then use standard WordPress functions to get any additional information you need.
