### ISSUE TITLE
Have 2nd Featured Image Be Only The Thumbnail on Home and Category Pages?

### ISSUE THREAD

**Issue by Nick555** [voceconnect/multi-post-thumbnails#116]
I use Genesis and i cannot figure out where to paste this snippet so the 2nd featured image shows only as the thumbnail on the home and category pages. Please help. http://factualfairytale.com/

`<?php 

if (class_exists('MultiPostThumbnails')) : 

MultiPostThumbnails::the_post_thumbnail(get_post_type(), 'secondary-image');

endif;

 ?>`

Can you please tell me exactly which folder and line to past this code so the second featured image displays as the thumbnail on the homepage and categories pages?

**Comment by dimbak** [comment]
not sure if i got your question but you may be looking for conditional tags https://codex.wordpress.org/Conditional_Tags
