### ISSUE TITLE
Installed the Plugin but no functionality in the post

### ISSUE THREAD

**Issue by siDM69** [voceconnect/multi-post-thumbnails#117]
Hi all. I have installed the plugin but still there is only option of featured image. How can i get the multiple images? Attaching the preview also.
![wordpress](https://cloud.githubusercontent.com/assets/26296331/23740748/d8750346-04c6-11e7-90f4-fc0c2f157cb8.JPG)

**Comment by chrisscott** [comment]
Have you gone through the steps [here](https://github.com/voceconnect/multi-post-thumbnails/wiki) to add the code to your theme?
