### ISSUE TITLE
Image size to display not working 

### ISSUE THREAD

**Issue by ushergrey** [voceconnect/multi-post-thumbnails#122]
Hi, 

Very Useful and awesome plugin. Image size to display not working. Need help.

This is my code.

functions.php
-------------------------------------------------
`	add_theme_support( 'post-thumbnails' );`
`	set_post_thumbnail_size( 480, 240, true );`
`add_image_size( 'post-thumbnail-768', 768, 384, true );`

front-page.php
--------------------------------------------------

`<?php if (class_exists('MultiPostThumbnails')) :`
`MultiPostThumbnails::the_post_thumbnail( get_post_type(), 'secondary-image', 'post-thumbnail' );`
`endif; ?>`

I want to set a custom size.  If I set the  **'post-thumbnail'** or **'post-thumbnail-768'** it will not be working.

Also, the backend **Secondary Image** size also not showing correctly.  

Please need your help

Thanx

**Comment by chrisscott** [comment]
The thumbnail size is the [fourth argument](https://github.com/voceconnect/multi-post-thumbnails/wiki#display-the-thumbnail) to `MultiPostThumbnails::the_post_thumbnail()` so you'd need to set that and use `null` as the third argument and it should work.

**Comment by ushergrey** [comment]
Hi,

Thank you very much it, worked. 

Another issue in **multi-post-thumbnails-admin.js (line 45, col 8)**

`TypeError: win.MultiPostThumbnails is undefined.`

`win.MultiPostThumbnails.setThumbnailID(thumb_id, id, post_type);`
` win.MultiPostThumbnails.setThumbnailHTML(str, id, post_type);`

I just remove the **win.** in both lines. it worked. I think you should update the plugin in WordPress repository.


Thanx.
