### ISSUE TITLE
Update to work with Block Editor

### ISSUE THREAD

**Issue by szczys** [voceconnect/multi-post-thumbnails#150]
Wordpress is moving toward the Gutenberg block editor. Multi-post-thumbnails has a performance quirk with the block editor:

- When a post in the block editor for the very first time the additional thumbnail dialogs are on the right sidebar of the editor window but do not look quite like the other sidebar widgets
- If you click the up/down arrows on the widgets to move them to a different order in the sidebar they disappear and move to the area under the block editor
- There is no way to move these back to the sidebar
- Widgets make the most sense in the sidebar as this is where the "Featured Image" widget is found.

This should be fix. I'm looking into it but my unfamiliarity with the plugin code base makes this a slow process.

**Comment by szczys** [comment]
It's likely that meta_boxes are what have changed and need to be converted to blocks:
https://developer.wordpress.org/block-editor/developers/backward-compatibility/meta-box/

**Comment by rickcurran** [comment]
I'm not seeing the behaviour you're seeing. I have the additional thumbnail meta boxes on the right hand side, I can move them up and down and they stay on the right hand side. Meta boxes still work pretty much as before even with the block editor, so this should still work the same. Does this only happen to you for the multi-post thumbnail meta boxes? If you have any others it would be worth seeing if the same thing happened. It might be also worth checking if you've got any other plugins or code in your theme that might affect the behaviour of meta boxes in case there's something else affecting them here.

**Comment by szczys** [comment]
Thanks for testing this.

I tried it again and it seems the right sidebar meta box moves out of the sidebar and below the block editor area when you click the meta box up arrow and it is the top item that can be adjusted. Here is what those sidebar meta boxes look like for me, in this example clicking the up arrow on Blogview Image moves the metabox out of the sidebar:
![Screenshot from 2020-11-24 11-43-14](https://user-images.githubusercontent.com/367685/100132007-6f9dc400-2e4a-11eb-893f-d07ad3b3057c.png)

Yes, I do have one other plugin whose meta box is missing from the gutenberg editor completely. I'll test turning off all plugins and see if that narrows down the cause.

Edit:
Seems you can drag those boxes back into the bottom of the sidebar. But overall I think the difference in look and behavior of these boxes indicates that the approach is deprecated and should be updated to where Wordpress is going with Gutenberg. It looks like there are hooks for old and new so this should be possible without breaking it for people sticking with MCE editor.

**Comment by szczys** [comment]
So it looks like meta boxes are still supported by Gutenberg. This is just a styling bug and there is already an issue for it in the tracker:
https://core.trac.wordpress.org/ticket/51284
