### ISSUE TITLE
Unable to add a class to the image

### ISSUE THREAD

**Issue by David-Streck** [voceconnect/multi-post-thumbnails#20]

**Comment by pedromarqueslx** [comment]
<?php
                                                    if (class_exists('MultiPostThumbnails')) :
                                                    MultiPostThumbnails::the_post_thumbnail( get_post_type(), 'secondary-image', null, 'post-thumbnail', array('class' => 'img-fluid'));
                                                    endif;
                                                    ?>


Thanks! That works!!! :)
