### ISSUE TITLE
Admin thumbnail display

### ISSUE THREAD

**Issue by Oslaf** [voceconnect/multi-post-thumbnails#44]
Hugely shallow thing to request, but could the post thumbnail preview image in the admin be styled so it doesn't overflow beyond the padding of the container if it's too wide? It's kind of a visual eyesore when using the extra thumbnail with landscape-style images.

**Comment by Justin-Marks** [comment]
Can you change this from `width: 100%` to  `max-width: 100%` instead? Because this is making small images huge and blurry.

**Comment by chrisscott** [comment]
Updated in 1.6.5. Pushing to .org shortly.
