### ISSUE TITLE
MPT breaks when trying to edit image

### ISSUE THREAD

**Issue by rohitsodhia** [voceconnect/multi-post-thumbnails#48]
In my office we're running 3.9.2. We're able to create a new thumbnail with MPT, but when we select an image and hit the "Edit Image" button on the side bar, instead of opening up in the main media frame like it does for the standardfeatured image, instead it opens up in a new window, making for a poor interaction.

We're hoping you might have some thoughts to this, or any fixes.

**Comment by chrisscott** [comment]
Closing due to age. Please re-open if needed.
