### ISSUE TITLE
Exporting thumbnail images with custom post types

### ISSUE THREAD

**Issue by deardooley** [voceconnect/multi-post-thumbnails#52]
Thanks for the great work on this plugin. I have an issue/feature request. I need to export several custom post types which use this plugin. The problem I run into is that the images do not export with the post types. The custom metadata exports fine, but the images do not. I realize this is technically due to the way the native wordpress exporter works, but I believe the problem actually boils down to the manner in which the plugin associates images with post types. I can think of two possible solutions off the top of my head. 

1. Provide a custom exporter plugin to work around this situation when users export partial content from their blogs.
2. Force an association between every thumbnail with its parent post type. In situations where the image is already associated with a post type, duplicate it and associate the copy with the post type.

I've prototyped them both, and they work, but neither feels like a good general solution. I'd like to hear your thoughts.

**Comment by chrisscott** [comment]
As you noted, this is a limitation of the exporter since any partial export doesn't check (natively or through allowance by a filter) for any attached or associated (through metadata) attachments and add them to the WXR. Solution 1 definitely seems like the clean option to me.

**Comment by deardooley** [comment]
If I work that into the existing plugin via a settings panel, would you accept the pull request, or would you rather it be an external thing to handle file attachments in a more general way?

Rion

**Comment by chrisscott** [comment]
I think a separate plugin would make sense since this has a broader use case outside this plugin and would probably be more valuable as a standalone.

**Comment by dav086** [comment]
@deardooley did you manage to come up with a solution for this at all? I'm in the same boat at the moment, and could definitely do with an export solution...

**Comment by deardooley** [comment]
@dav086 Yes. I wound up forking [demomentsomtres-wp-export]() and adding in support for the things I needed. There are some schema issues in wordpress that prevent this from being done cleanly as in other posts. Message me offline if you'd like a copy.

**Comment by dav086** [comment]
@deardooley I'd love a copy please! Although I can't work out how to message you on Github other than through this board, sorry. My email address is on my profile for the time being. Thanks a lot :+1:

**Comment by deardooley** [comment]
On it's way. For posterity, those of you reading this thread in the future should checked out the [Wordpress REST API](https://developer.wordpress.com/docs/api/). There's a great tutorial and slide deck by @petenelson about [Extending the Wordpress API](https://github.com/petenelson/extending-wp-rest-api) and bending it to your will from his talk at the Austin Wordpress Meetup.
