### ISSUE TITLE
Could not set that as the thumbnail image message

### ISSUE THREAD

**Issue by jvivona** [voceconnect/multi-post-thumbnails#55]
running the plugin inside of CherryFramework.  Added this code to the post-type init
<code>   new MultiPostThumbnails(
        array(
            'label' => 'Formal (Interior) Image',
            'id' => 'team-secondary-image',
            'post_type' => 'ourteamfolio'
        )
    );
</code>

Can see the meta-box like I am expecting. 
![image](https://cloud.githubusercontent.com/assets/1454249/6371849/99b7e10c-bccd-11e4-9b40-5bdccbf7a983.png)

 When I try to set the image, for all images in our site - I keep getting a javascript pop-up which says "Could not set that as the thumbnail image, try another image" message box.

![image](https://cloud.githubusercontent.com/assets/1454249/6371846/9026ae3e-bccd-11e4-9fee-2a145509021b.png)

Any thoughts?

**Comment by chrisscott** [comment]
There's a couple things to check:
* Make sure your code to register the thumbnail in your `functions.php` is outside of any other code or hooks (the only hook that it will reliably work with is `wp_loaded`)
* Check your database to see if any tables need repairing
* Try disabling all other plugins but MPT and if it then works, re-enable the plugins one by one to narrow down which one is conflicting

Hope this helps.

**Comment by jvivona** [comment]
Yup - even though in the instructions, you said it 3 times, I still ignored your directive to put it outside the hooks.  The minute I moved it, problem solved...   So very odd..

Thanks!
