### ISSUE TITLE
Image not selected in media lightbox

### ISSUE THREAD

**Issue by yliharma** [voceconnect/multi-post-thumbnails#59]
If I click on a MultiPostThumbnail from inside the post edit page (after having set it and saved the post), wordpress opens a lightbox, but the image is not selected (see the attached screenshot).
![schermata 2015-04-22 a 16 31 52](https://cloud.githubusercontent.com/assets/6401290/7277259/62ad02dc-e90f-11e4-9d80-2116923ce782.png)

**Comment by chrisscott** [comment]
Closing due to age. Please re-open if needed.
