### ISSUE TITLE
Are you aware add_query_arg issue ?

### ISSUE THREAD

**Issue by xpeeder** [voceconnect/multi-post-thumbnails#60]
your plugin also available add_query_arg() and remove_query_arg()
if your plugin need update
https://make.wordpress.org/plugins/2015/04/20/fixing-add_query_arg-and-remove_query_arg-usage/
https://blog.sucuri.net/2015/04/security-advisory-xss-vulnerability-affecting-multiple-wordpress-plugins.html

Thanks :)

**Comment by prettyboymp** [comment]
fixed in https://github.com/voceconnect/multi-post-thumbnails/commit/aa11983de24529e4c0bbbe1821573c9abaf2f104

**Comment by xpeeder** [comment]
Thanks mate :100:   ☕
