### ISSUE TITLE
Add attributes to the link

### ISSUE THREAD

**Issue by lumpysimon** [voceconnect/multi-post-thumbnails#61]
Would it be possible to add an option to the `the_post_thumbnail` and `get_the_post_thumbnail` methods to add attributes to the link (in the same way that attributes can be added to the image)?

I've got three featured images per post and using fancyBox to display them when clicked, but I need the `rel="group"` attribute on the links so that fancyBox groups them to give the prev/next navigation in the lightbox.

At the moment I'm using jQuery to add the attributes which works fine, but it would be nice if this could be done via the methods.

**Comment by chrisscott** [comment]
Closing due to age. Please re-open if needed.
