### ISSUE TITLE
Multipost return values

### ISSUE THREAD

**Issue by anteloff** [voceconnect/multi-post-thumbnails#64]
Hi,
thanks for great plugin!

I have one question, since I'm using multipost plugin to display images in slider (3 slides, 1 image for each). Slider is coded into single.php template file, and I call multipost thumbnail image in each slide, example : 

<div class="slideDemo">
<?php if (class_exists('MultiPostThumbnails')) : MultiPostThumbnails::the_post_thumbnail( get_post_type(), 'project-image3' ); endif; ?>
</div>

So, I would like to check if multipost item "project-image3" exists, and if it does, I'd like to show slide. If it doesn't exist, slide shouldn't be visible.

Thanks in advance!
Ante.

**Comment by chrisscott** [comment]
You can use the value of `MultiPostThumbnails ::get_the_post_thumbnail()` to determine this. If there is no thumbnail the return value will be a blank string.
