### ISSUE TITLE
Pulling featured image id's

### ISSUE THREAD

**Issue by jameshiggins** [voceconnect/multi-post-thumbnails#65]
Hi,

I'm using a slider which requests image ids to create the slides.

How could I request individually or in an array the ids from registered post thumbnails?

Thanks,

**Comment by chrisscott** [comment]
You can use the `MultiPostThumbnails:: get_post_thumbnail_id()` ([more info](https://github.com/voceconnect/multi-post-thumbnails/wiki/Functions-and-Template-Tags#get_post_thumbnail_id)) function to get the ID of any registered thumbnail for a given post.

**Comment by jameshiggins** [comment]
Thanks, figured it out.


-J

James Higgins
Web Developer

<http://jameshiggins.ca/>

British Columbia, Canada

 [image: jamesallenhiggins] [image: Displaying linkedin_sig.gif]
<http://www.linkedin.com/pub/james-higgins/27/9aa/85>
