### ISSUE TITLE
Returning the image URL without the tag

### ISSUE THREAD

**Issue by estellechvl** [voceconnect/multi-post-thumbnails#67]
Im trying to <strong>return in my template the secondary image URL</strong> to inject it with inline CSS as a background.

Is there any way to do so ? So far i've tried this, but it doesnt work : 

```
<div class="article-img" style=" background-image: url(
	<?php if (class_exists('MultiPostThumbnails')) :
		$custom = MultiPostThumbnails::get_post_thumbnail_id(‘post’,   ‘secondary-image’, $post->ID); 
		$custom=wp_get_attachment_image_src($custom,’post-secondary-image-thumbnail’); echo $custom[0];
	endif; ?>); background-size:cover;">
</div>
```

thank you :)

**Comment by chrisscott** [comment]
You can use `MultiPostThumbnails::get_post_thumbnail_url()` to do this. See [the docs](https://github.com/voceconnect/multi-post-thumbnails/wiki/Functions-and-Template-Tags#get_post_thumbnail_url) for more info.
