### ISSUE TITLE
(Solved! Thanks @chrisscott) Not  functioning as usual.

### ISSUE THREAD

**Issue by brandwebdesign** [voceconnect/multi-post-thumbnails#81]
I've used this plugin in the past, it worked great! Unfortunately, it isn't functioning as expected. When I click the add second featured image link, the current edit screen is just refreshed, the media lightbox does not open.

**Comment by chrisscott** [comment]
Do you get any javascript errors in the console?

**Comment by brandwebdesign** [comment]
Yes, they are:
09:48:23.285 ReferenceError: jQuery is not defined...load-scripts.php:10:25
09:48:23.395 TypeError: wp.media is undefined...media-modal.js:9:3
09:48:23.518 TypeError: wp.media is undefined...load-scripts.php:386:4795
Thanks for your help.

**Comment by chrisscott** [comment]
Do you see requests in the network panel for those js files? If so, are they giving 200 or 404 or 500 or...? And if they are 404ing, what are the paths? It may be the path detection isn't working.

**Comment by brandwebdesign** [comment]
The first gives a 200, the second a 304, and the third a 200.

**Comment by chrisscott** [comment]
The `ReferenceError: jQuery is not defined...wp-admin/load-scripts.php:10:25` part seems like something may be unregistering/unqueuing jQuery. If you disable all other plugins, do you still see the same error? Also, have you forced+refresh to clear your browser cache or tested on other browsers? Finally, what version of the plugin and WordPress are you using?

**Comment by brandwebdesign** [comment]
Yes I have cleared my browser's cache. I have tested by disabling all other plugins. I actively use the latest Firefox, running on the latest OSX, but have also tried testing in the latest Chrome. The issue still persists.

**Comment by brandwebdesign** [comment]
I solved it! I think anyways. I had jquery being deregistered on the admin in my functions file. It was a leftover snippet, from a previous application I built. This will teach my to test my theme first. Thanks for your time! I really appreciate it.
