### ISSUE TITLE
Help needed changing to secondary featured img on hover

### ISSUE THREAD

**Issue by feeluna** [voceconnect/multi-post-thumbnails#88]
hi there! i've been trying to change the thumbnails of my post's featured images to the secondary featured image on mouse-hover.

installing the multiple post thumbnail plugin worked fine, i can select a secondary image but i'm having trouble implementing that hover option/effect.

SUMMARY:
-theme: Salient
-plugin for secondary featured image: Multiple Post Thmbnails (https://de.wordpress.org/plugins/multiple-post-thumbnails/)
-tutorial i tried to use: http://www.scratchinginfo.net/hover-two-featured-images-wordpress-via-multiple-post-thumbnails-plugin/
-link to my texting-site: http://feeluna.com/offline/
-problem: when i hover over one of the thumbnails, i want the secondary image to appear, currently only the posts named 'TEST...' have a secondary thumbnail selected.

we would be grateful for help and would like to pay you back for the favour!

here's what my clean index, header, functions and style looks like:
[support-themefiles.zip](https://github.com/voceconnect/multi-post-thumbnails/files/165513/support-themefiles.zip)

**Comment by chrisscott** [comment]
If you can post code samples with only the thumbnail registration portion from functions.php and the output in your theme's template it would be helpful.

**Comment by feeluna** [comment]
@chrisscott thanks! i posted a zip with my theme's code...
i posted this portion in my functions php:

```
if (class_exists('MultiPostThumbnails')) {
        new MultiPostThumbnails(
            array(
                'label' =&gt; 'Secondary Image',
                'id' =&gt; 'secondary-image',
                'post_type' =&gt; 'post'
            )
        );
    }
```

i experimented with one of the twentyfifteen themes, and i managed to include the second image in there. so the problem is that my second image is not displaying on the salient-theme.

i used your plug-in in hopes to archiving a hover-effect such as: http://www.floriasigismondi.com/photo/
where a second featured image will only be displayed upon mouse-over. i read it should be possible with additory jquery script. :(
