### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by derrinleejones** [voceconnect/multi-post-thumbnails#91]
I am having issues with this plugin. I am trying to use  "Multiple Post Thumbnails" plugin so that I can have more than one featured image per product. Then I will display a certain featured image depending on which category is viewed on the shop page. 

The plugin states that add_theme_support( 'post-thumbnails' ); must be enabled in functions.php (which I have done). I have tried to both activate the plugin and to directly integrate into theme, neither work.
When viewing products, the extra featured image boxes do not show. I have tried purging the cache and the cdn cache, not working.
 Thoughts on why this may be?

Theme: Flatsome (child - Placing any functions.php calls in child functions.php)
Wordpress 4.4.2
Woocommerce 2.5.5

**Comment by chrisscott** [comment]
Make sure you've followed the instructions here to register and output the thumbnail: https://github.com/voceconnect/multi-post-thumbnails/wiki#quick-start
