### ISSUE TITLE
i have Not getting secondary image on blog page header (Posts page).

### ISSUE THREAD

**Issue by rvpatel** [voceconnect/multi-post-thumbnails#93]
I have manage setting Posts page: as Blog.
Then i have attach image on blog page "secondary image" but not getting on header.

For other pages work only blog page(Posts page) on issue.

**Comment by chrisscott** [comment]
If you're trying to display a thumbnail outside of a post loop you'll need to pass in the `$post_id` of the post you want to display the thumbnail for as the 3rd argument to `MultiPostThumbnails::the_post_thumbnail()`.

**Comment by rvpatel** [comment]
I have added code with page id for post page (blog) but not working

**Comment by chrisscott** [comment]
What is the code?
