### ISSUE TITLE
it stopped work with wp 4.5

### ISSUE THREAD

**Issue by eltonbaroncello** [voceconnect/multi-post-thumbnails#96]
Plugin it was working before update to wordpress 4.5.

**Comment by chrisscott** [comment]
I'm not having any problems using it in 4.5. Can you provide details on what isn't working?

**Comment by eltonbaroncello** [comment]
I've this on function.php

```
if(class_exists('MultiPostThumbnails')) {
	new MultiPostThumbnails(
		array(
			'label' => 'Slide Imagem',
			'id' => 'slide-thumbnail',
			'post_type' => 'eventos'
		)
	);
}
```

and it doesn't even display anymore the widget on dashboard add/edit post

**Comment by matgargano** [comment]
Is the plugin enabled?

**Comment by eltonbaroncello** [comment]
yes! apparently the bug it's only on wordpress multisite installation.  it's working in the regular wp installation

**Comment by chrisscott** [comment]
Make sure you have the plugin network enabled if using it on a site that isn't the main site.

**Comment by twwli** [comment]
Same problem here with Wordpress 4.5.
When the plugin is activated, I've an Internal Server Error (Error 500). Everything was fine until now...

**Comment by chrisscott** [comment]
@twwli  can you check your server/php error logs to see if there's any details on the error in there?

**Comment by chrisscott** [comment]
Closing this since it has been a while but please re-open if this is still a problem and you have more details on errors or how to reproduce.
