### ISSUE TITLE
is "get_post_thumbnail_url" not working?

### ISSUE THREAD

**Issue by masterjkk** [voceconnect/multi-post-thumbnails#97]
I use "if (class_exists('MultiPostThumbnails'))  : MultiPostThumbnails::get_post_thumbnail_url(get_post_type(), 'secondary-image'); "

but it seems to be no responding url.

why?

**Comment by nestor-santana** [comment]
This feature is broken and there has not been an update proposed. So, you cannot echo the URL alone as it stands.

**Comment by chrisscott** [comment]
@masterjkk if you're expecting that to print the URL, you'll need to echo it. Like core's `get_` vs. `the_` template tags only `the_` echoes the result.

**Comment by masterjkk** [comment]
@nestor-santana happy to have your reply, it works well. Thanks! I also hope the author make a bugfix about it.

**Comment by masterjkk** [comment]
@chrisscott  thank you!

**Comment by chrisscott** [comment]
Closing since it doesn't seem like this is a bug but please re-open if I'm mistaken.
